[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
known_django = "django"
known_first_party = ["glossary"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = ["*/migrations/*"]
